#!/bin/bash

source "../../../set_tools.sh"

cp ${nmldir}/*.nml ./

#--------------------------------
# MOMturb.nml
#--------------------------------
# airsea.nml
nml="airsea.nml"
${cmd_nmlchange} -f ${nml} -e heat_method -v 2
${cmd_nmlchange} -f ${nml} -e heatflux_file -v 'heatflux_file.dat'
${cmd_nmlchange} -f ${nml} -e albedo_method -v 0
${cmd_nmlchange} -f ${nml} -e swr_method -v 2
${cmd_nmlchange} -f ${nml} -e swr_file -v 'swr_file.dat'
${cmd_nmlchange} -f ${nml} -e momentum_method -v 2
${cmd_nmlchange} -f ${nml} -e momentumflux_file -v 'tau_file.dat'
${cmd_nmlchange} -f ${nml} -e precip_method -v 2
${cmd_nmlchange} -f ${nml} -e precip_file -v 'precip_file.dat'
${cmd_nmlchange} -f ${nml} -e precip_factor -v 2.77778e-7
${cmd_nmlchange} -f ${nml} -e sst_method -v 2
${cmd_nmlchange} -f ${nml} -e sst_file -v 'sst_file.dat'
${cmd_nmlchange} -f ${nml} -e sss_method -v 2
${cmd_nmlchange} -f ${nml} -e sss_file -v 'sss_file.dat'
${cmd_nmlchange} -f ${nml} -e u10_method -v 2
${cmd_nmlchange} -f ${nml} -e u10_file -v 'u10_file.dat'
#--------------------------------
# epbl.nml
#--------------------------------
# gotmmean.nml
#--------------------------------
# gotmrun.nml
nml="gotmrun.nml"
${cmd_nmlchange} -f ${nml} -e title -v 'OCSPapa'
${cmd_nmlchange} -f ${nml} -e nlev -v 150
${cmd_nmlchange} -f ${nml} -e dt -v 1800
${cmd_nmlchange} -f ${nml} -e name -v 'OCSPapa'
${cmd_nmlchange} -f ${nml} -e latitude -v 50.1
${cmd_nmlchange} -f ${nml} -e longitude -v 215.1
${cmd_nmlchange} -f ${nml} -e depth -v 150.0
${cmd_nmlchange} -f ${nml} -e start -v '2012-01-01 00:00:00'
${cmd_nmlchange} -f ${nml} -e stop -v '2013-12-04 19:00:00'
${cmd_nmlchange} -f ${nml} -e nsave -v 6
${cmd_nmlchange} -f ${nml} -e eq_state_method -v 4
#--------------------------------
# gotmturb.nml
#--------------------------------
# jhl.nml
#--------------------------------
# kpp.nml
#--------------------------------
# langmuir.nml
nml="langmuir.nml"
${cmd_nmlchange} -f ${nml} -e langmuir_number_method -v 3
#--------------------------------
# obs.nml
nml="obs.nml"
${cmd_nmlchange} -f ${nml} -e s_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e s_prof_file -v 'sprof_file.dat'
${cmd_nmlchange} -f ${nml} -e t_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e t_prof_file -v 'tprof_file.dat'
${cmd_nmlchange} -f ${nml} -e us_prof_method -v 3
${cmd_nmlchange} -f ${nml} -e nfreq -v 64
${cmd_nmlchange} -f ${nml} -e spec_file -v 'spec_file.dat'
#--------------------------------
# osm.nml
nml="osm.nml"
${cmd_nmlchange} -f ${nml} -e h_i -v 20.0
#--------------------------------
# seagrass.nml
#--------------------------------
