#!/bin/bash

source "../../set_tools.sh"

cp ../../namelist/*.nml ./

#--------------------------------
# MOMturb.nml
#--------------------------------
# airsea.nml
#nml="airsea.nml"
#${cmd_nmlchange} -f ${nml} -e heat_method -v 2
#${cmd_nmlchange} -f ${nml} -e heatflux_file -v 'heatflux_file.dat'
#${cmd_nmlchange} -f ${nml} -e swr_method -v 2
#${cmd_nmlchange} -f ${nml} -e albedo_method -v 0
#${cmd_nmlchange} -f ${nml} -e swr_file -v 'swr_file.dat'
#${cmd_nmlchange} -f ${nml} -e momentum_method -v 2
#${cmd_nmlchange} -f ${nml} -e const_tx -v 0.1027
#${cmd_nmlchange} -f ${nml} -e momentumflux_file -v 'tau_file.dat'
#${cmd_nmlchange} -f ${nml} -e precip_method -v 2
#${cmd_nmlchange} -f ${nml} -e precip_file -v 'precip_file.dat'
#${cmd_nmlchange} -f ${nml} -e const_u10 -v 10
#--------------------------------
# epbl.nml
#--------------------------------
# gotmmean.nml
#--------------------------------
# gotmrun.nml
nml="gotmrun.nml"
${cmd_nmlchange} -f ${nml} -e title -v 'MISOBoB'
${cmd_nmlchange} -f ${nml} -e nlev -v 100
#${cmd_nmlchange} -f ${nml} -e dt -v 1800
${cmd_nmlchange} -f ${nml} -e name -v 'MISOBoB'
#${cmd_nmlchange} -f ${nml} -e latitude -v -14
#${cmd_nmlchange} -f ${nml} -e longitude -v 88.0
#${cmd_nmlchange} -f ${nml} -e depth -v 160.0
#${cmd_nmlchange} -f ${nml} -e MaxN -v 800
#${cmd_nmlchange} -f ${nml} -e start -v '2006-08-03 01:25:00'
#${cmd_nmlchange} -f ${nml} -e stop -v '2006-08-05 12:03:00'
${cmd_nmlchange} -f ${nml} -e out_fn -v 'gotm_out'
${cmd_nmlchange} -f ${nml} -e nsave -v 1
#${cmd_nmlchange} -f ${nml} -e sync_out -v 0
#${cmd_nmlchange} -f ${nml} -e eq_state_method -v 4
#--------------------------------
# gotmturb.nml
#--------------------------------
# jhl.nml
#--------------------------------
# kpp.nml
#--------------------------------
#  langmuir.nml
#nml="langmuir.nml"
#${cmd_nmlchange} -f ${nml} -e langmuir_number_method -v 4
#--------------------------------
# obs.nml
#nml="obs.nml"
#${cmd_nmlchange} -f ${nml} -e s_prof_method -v 2
#${cmd_nmlchange} -f ${nml} -e s_prof_file -v 'sprof_file.dat'
#${cmd_nmlchange} -f ${nml} -e t_prof_method -v 2
#${cmd_nmlchange} -f ${nml} -e t_prof_file -v 'tprof_file.dat'
#${cmd_nmlchange} -f ${nml} -e extinct_method -v 7
#${cmd_nmlchange} -f ${nml} -e A -v 0.57
#${cmd_nmlchange} -f ${nml} -e g1 -v 0.5
#${cmd_nmlchange} -f ${nml} -e g2 -v 13.4
#${cmd_nmlchange} -f ${nml} -e ustokes_method -v 4
#${cmd_nmlchange} -f ${nml} -e nfreq -v 1
#${cmd_nmlchange} -f ${nml} -e usdelta_file -v 'ustokes_file.dat'
#--------------------------------
# osm.nml
#nml="osm.nml"
#${cmd_nmlchange} -f ${nml} -e h_i -v 13.0
#--------------------------------
# seagrass.nml
#--------------------------------
