#!/bin/bash
# Run GOTM using with idealized forcing and initial conditions
# from Li and Fox-Kemper, 2017
#
#######################################################################
#                           parse arguments                           #
#######################################################################
turbmethod="none"

while getopts m: options
do
    case $options in
        # turbulence model
        m) turbmethod=$OPTARG ;;
        \?) echo "Unknown option -$OPTARG"
            exit 1 ;;
    esac
done

if [[ ${turbmethod} == "none" ]]; then
    echo "Missing option -m [turbulence model]"
    exit 1
fi

#######################################################################
#                              Set paths                              #
#######################################################################

# setup paths and tools
source "../../set_tools.sh"

# directory of base case
basecase="${GOTMWORK_ROOT}/data/Idealized_Tests_LF17"

#######################################################################
#                           Set parameters                            #
#######################################################################

# case name
casename="LF17"

# output file name
outname="gotm_out"

# set levels
nlev=256
depth=163.84
ddu=0.0
ddl=0.0

# set Coriolis
latitude=45

# run parameters
dt=60.0
nsave=15

# starting and ending date - in the format of YYYYMMDD
datestart="20000101"
dateend="20000103"

# heat flux (W/m^2)
heatflux_labels=( "BF05" "BF10" "BF25" "BF50" "BF1h" "BF2h" "BF3h" "BF5h" )
heatflux_list=( -5.0 -10.0 -25.0 -50.0 -100.0 -200.0 -300.0 -500.0 )

# 10-meter wind (m/s)
wind_labels=( "WD05" "WD08" "WD10"  )
taux_list=( 0.036 0.09216 0.144 )
tauy_list=( 0.0 0.0 0.0 )
u10_list=( 5.0 8.0 10.0 )
v10_list=( 0.0 0.0 0.0)

# wave age (unitless, DHH spectrum)
wave_labels=( "WV00" "WV01" "WV02" "WV03" "WV04" )
wave_age_list=( 1.2 1.2 1.0 0.8 0.6 )

#######################################################################
#                         Loop over all cases                         #
#######################################################################

for i in ${!heatflux_labels[@]}
do
    # surface buoyancy forcing
    heatflux=${heatflux_list[i]}
    for j in ${!wind_labels[@]}
    do
        # wind forcing
        taux=${taux_list[j]}
        tauy=${tauy_list[j]}
        u10=${u10_list[j]}
        v10=${v10_list[j]}
        for k in ${!wave_labels[@]}
        do
            # wave forcing
            wave_age=${wave_age_list[k]}

            # turn off waves for WV00
            if [[ ${k} == 0 ]]; then
                ustokes_method=0
            else
                ustokes_method=7
            fi

            # label for surface forcing
            sf_label="R7_${heatflux_labels[i]}${wind_labels[j]}${wave_labels[k]}"
            echo ${sf_label}

            # title  of the simulation
            title="${casename}_${sf_label}_${turbmethod}"

            # create run directory
            rundir="${GOTMRUN_ROOT}/Idealized_Tests/${casename}/${turbmethod}/${sf_label}"
            mkdir -p ${rundir}
            cd ${rundir}

            # copy base case
            cp ${basecase}/*.nml ./
            cp ${basecase}/*.dat ./

            # set run parameters
            start_time="${datestart:0:4}-${datestart:4:2}-${datestart:6:2} 00:00:00"
            stop_time="${dateend:0:4}-${dateend:4:2}-${dateend:6:2} 00:00:00"
            ${cmd_nmlchange} -f gotmrun.nml -e start -v "${start_time}"
            ${cmd_nmlchange} -f gotmrun.nml -e stop -v "${stop_time}"
            ${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
            ${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
            ${cmd_nmlchange} -f gotmrun.nml -e dt -v ${dt}
            ${cmd_nmlchange} -f gotmrun.nml -e nsave -v ${nsave}
            ${cmd_nmlchange} -f gotmrun.nml -e nlev -v ${nlev}
            ${cmd_nmlchange} -f gotmrun.nml -e depth -v ${depth}
            ${cmd_nmlchange} -f gotmrun.nml -e latitude -v ${latitude}
            ${cmd_nmlchange} -f gotmmean.nml -e ddu -v ${ddu}
            ${cmd_nmlchange} -f gotmmean.nml -e ddl -v ${ddl}
            ${cmd_nmlchange} -f airsea.nml -e u10_method -v 1
            ${cmd_nmlchange} -f airsea.nml -e const_u10 -v ${u10}
            ${cmd_nmlchange} -f airsea.nml -e const_v10 -v ${v10}
            ${cmd_nmlchange} -f airsea.nml -e momentum_method -v 1
            ${cmd_nmlchange} -f airsea.nml -e const_tx -v ${taux}
            ${cmd_nmlchange} -f airsea.nml -e const_ty -v ${tauy}
            ${cmd_nmlchange} -f airsea.nml -e heat_method -v 1
            ${cmd_nmlchange} -f airsea.nml -e const_heat -v ${heatflux}
            ${cmd_nmlchange} -f obs.nml -e ustokes_method -v ${ustokes_method}
            ${cmd_nmlchange} -f obs.nml -e wave_age -v ${wave_age}

            # set turbulence method
            source ${scpt_case_turbmethod}

            # run gotm
            ${cmd_gotm} 2> log.${outname}

        done
    done
done
