#!/bin/bash
# Setup and run GOTM for OCS KEO
#
# Qing Li, 20171211

#######################################################################
#                              Set paths                              #
#######################################################################

# setup paths and tools
source "../../set_tools.sh"

# input data - surface fluxes
datadir="${GOTMDATA_ROOT}/OCS/KEO/KEO_2008-2009"

# current path
curdir=$(pwd)

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="OCSKEO"

# set levels, grid zooming at surface
nlev=128
ddu=2
ddl=0

# run parameters
dt=1800
nsave=6

# output file name
outname="gotm_out"

# starting and ending date - in the format of YYYYMMDD
datestart="20080701"
dateend="20081231"

# name of the turbulence model
turbmethod="KPP-CVMix"
# turbmethod="KPP-GOTM"

# case name
casename="${title}_${turbmethod}_${datestart}-${dateend}"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${GOTMRUN_ROOT}/${casename}"
mkdir -p ${rundir}
cd ${rundir}

# set up namelists
cp ${nmldir}/*.nml ./

# set run parameters
xmlfile=${title}.xml
cp ${xmldir}/${xmlfile} ./
${cmd_case_preproc} -xml ${xmlfile} -root ${GOTMWORK_ROOT} -data ${datadir} \
    -ds ${datestart} -de ${dateend}
${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
${cmd_nmlchange} -f gotmrun.nml -e dt -v ${dt}
${cmd_nmlchange} -f gotmrun.nml -e nsave -v ${nsave}
${cmd_nmlchange} -f gotmrun.nml -e nlev -v ${nlev}
${cmd_nmlchange} -f gotmmean.nml -e ddu -v ${ddu}
${cmd_nmlchange} -f gotmmean.nml -e ddl -v ${ddl}

# set turbulence model
case ${turbmethod} in
    "SMC")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 3
        ${cmd_nmlchange} -f gotmturb.nml -e tke_method -v 3
        ${cmd_nmlchange} -f gotmturb.nml -e len_scale_method -v 9
        ${cmd_nmlchange} -f gotmturb.nml -e scnd_coeff -v 3
        ;;
    "KPP-CVMix")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99
        ${cmd_nmlchange} -f kpp.nml -e lcvmix -v .true.
        ;;
    "KPP-GOTM")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99
        ${cmd_nmlchange} -f kpp.nml -e lcvmix -v .false.
        ;;
    *)
        echo "Turbulence method ${turbmethod} not supported. Stop."
        exit 1
esac

#######################################################################
#                              Run GOTM                               #
#######################################################################
${cmd_gotm} 2> log.${outname}

#######################################################################
#                           Post-processing                           #
#######################################################################

# plot surface forcing and profiles
source ${curdir}/case_postproc.sh
