#!/bin/bash
# Setup and run GOTM for OCS KEO
#
# Qing Li, 20171211

#######################################################################
#                              Set path                               #
#######################################################################

workdir="${HOME}/models/gotm/gotmwork"
tooldir="${workdir}/tools"
nmldir="${workdir}/namelist"
xmldir="${workdir}/data"
cmd_nc2dat="${tooldir}/nc2dat"
cmd_nmlchange="${tooldir}/nmlchange"
cmd_casepreproc="${tooldir}/casepreproc"

#######################################################################
#                           Set parameters                            #
#######################################################################

datadir="${HOME}/data/OCS/KEO/2016"
title="OCSKEO"
outname="ocskeo"
# start and end date
datestart="20160325"
dateend="20160411"

#######################################################################
#                        Preprocess input data                        #
#######################################################################
cp ${nmldir}/*.nml ./
# read data.xml
xmlfile=${title}.xml
cp ${xmldir}/${xmlfile} ./
${cmd_casepreproc} -i ${xmlfile} -root ${workdir} -data ${datadir} \
    -ds ${datestart} -de ${dateend}

${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
# ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99

#######################################################################
#                              Run GOTM                               #
#######################################################################
gotm 2> log.${outname}
