#!/bin/bash
# Setup and run GOTM for OCS Papa
#
# Qing Li, 20171105

#######################################################################
#                              Set paths                              #
#######################################################################

# root directory for gotmwork
workdir="${HOME}/models/gotm/gotmwork"

# scratch directory to run the case
scratchdir="${HOME}/work/gotmrun"

# setup paths and tools
source ${workdir}/set_tools.sh

# input data root directory
dataroot="${HOME}/work/gotmdata"

# input data - surface fluxes
datadir="${dataroot}/OCS/Papa/Papa_20100616-20150101"
# datadir="${dataroot}/OCS/Papa/Papa_2008-2009"

# input data - waves
specdata="${dataroot}/CDIP/Papa/166p1_historic.nc"

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="OCSPapa"

# set levels, grid zooming at surface
nlev=128
ddu=2
ddl=0

# run parameters
dt=1800
nsave=6

# output file name
outname="gotm_out"

# starting and ending date - in the format of YYYYMMDD
datestart="20130701"
dateend="20140701"

# name of the turbulence model
# turbmethod="KPPLT-EFACTOR"
# turbmethod="KPPLT-ENTR"
# turbmethod="KPP-Original"
turbmethod="SMCLT"
# turbmethod="SMC"

# case name
casename="${title}_${turbmethod}_${datestart}-${dateend}"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${scratchdir}/${casename}"
mkdir -p ${rundir}
cd ${rundir}

# set up namelists
cp ${nmldir}/*.nml ./

# set run parameters
xmlfile=${title}.xml
cp ${xmldir}/${xmlfile} ./
${cmd_case_preproc} -xml ${xmlfile} -root ${workdir} -data ${datadir} \
    -ds ${datestart} -de ${dateend}
${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
${cmd_nmlchange} -f gotmrun.nml -e dt -v ${dt}
${cmd_nmlchange} -f gotmrun.nml -e nsave -v ${nsave}
${cmd_nmlchange} -f gotmrun.nml -e nlev -v ${nlev}
${cmd_nmlchange} -f gotmmean.nml -e ddu -v ${ddu}
${cmd_nmlchange} -f gotmmean.nml -e ddl -v ${ddl}

# processing wave spectrum data
if [ ! -z ${specdata} ]; then
    # only do this if specdata is set
    ${cmd_nc2dat_cdip} -i ${specdata} -o "spec_file.dat" -ds ${datestart} \
        -de ${dateend}
    ${cmd_nmlchange} -f obs.nml -e ustokes_method -v 2
    ${cmd_nmlchange} -f obs.nml -e nfreq -v 64
    ${cmd_nmlchange} -f obs.nml -e spec_file -v 'spec_file.dat'
fi

# set turbulence model
case ${turbmethod} in
    "OSMOSIS")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 98
        ;;
    "SMC")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 3
        ${cmd_nmlchange} -f gotmturb.nml -e tke_method -v 3
        ${cmd_nmlchange} -f gotmturb.nml -e len_scale_method -v 9
        ${cmd_nmlchange} -f gotmturb.nml -e scnd_coeff -v 3
        ;;
    "SMCLT")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 3
        ${cmd_nmlchange} -f gotmturb.nml -e tke_method -v 4
        ${cmd_nmlchange} -f gotmturb.nml -e len_scale_method -v 11
        ${cmd_nmlchange} -f gotmturb.nml -e e6 -v 6.0
        ${cmd_nmlchange} -f gotmturb.nml -e scnd_coeff -v 3
        ;;
    "KPP-CVMix")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99
        ${cmd_nmlchange} -f kpp.nml -e lcvmix -v .true.
        ;;
    "KPP-GOTM")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99
        ${cmd_nmlchange} -f kpp.nml -e lcvmix -v .false.
        ;;
    "KPPLT-EFACTOR")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99
        ${cmd_nmlchange} -f kpp.nml -e lcvmix -v .true.
        ${cmd_nmlchange} -f kpp.nml -e langmuir_method -v 1
        ${cmd_nmlchange} -f kpp.nml -e efactor_method -v 3
        ;;
    "KPPLT-ENTR")
        ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99
        ${cmd_nmlchange} -f kpp.nml -e lcvmix -v .true.
        ${cmd_nmlchange} -f kpp.nml -e langmuir_method -v 2
        ${cmd_nmlchange} -f kpp.nml -e efactor_method -v 3
        ;;
    *)
        echo "Turbulence method ${turbmethod} not supported. Stop."
        exit 1
esac

#######################################################################
#                              Run GOTM                               #
#######################################################################
gotm 2> log.${outname}

#######################################################################
#                           Postprocessing                            #
#######################################################################

# plot surface forcing and profiles
source ${scpt_case_postproc}
