#!/bin/bash
# This script sets up test cases to test the sensitivity of different
# boundary layer schemes to vertical resolution and time step using
# forcing data from OSMOSIS
#
# OSMOSIS
# latitude:  49.0
# longitude: 0.0
# depth (m): 240.0 (spring)
#            200.0 (winter)
#
# Qing Li, 20180507

# root directory for gotmwork
workdir="${HOME}/models/gotm/gotmwork"

# scratch directory to run the case
scratchdir="${HOME}/work/gotmrun"

# setup paths and tools
source ${workdir}/set_tools.sh

# season (winter or spring)
for season in winter spring; do
    # directory of base case
    basecase="${workdir}/data/OSMOSIS_${season}"

    # name of the dataset
    title="OSMOSIS_${season}"

    # loop over cases
    source ./case_loop.sh
done
