#!/bin/bash
# Setup and run GOTM for CORE-II
#
# Qing Li, 20180307

#######################################################################
#                              Set path                               #
#######################################################################

# setup paths and tools
source "../../set_tools.sh"

# input data - surface fluxes
datadir="/Volumes/Qing_Work/data/yellowstone/b1850_f19_gx1_vr12-ma_v2"

# current path
curdir=$(pwd)

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="CESM"

# set locations
lat=50
lon=215
maxdepth=300

# output file name
outname="gotm_out"

# starting and ending date - in the format of YYYYMMDD
datestart="20090701"
dateend="20091231"

# name of the turbulence model
turbmethod="KPP-CVMix"
# turbmethod="KPP-GOTM"

# case name
casename="${title}_LAT${lat}_LON${lon}_${turbmethod}_${datestart}-${dateend}"

#
l_run_gotm="yes"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${GOTMRUN_ROOT}/${casename}"
mkdir -p ${rundir}
cd ${rundir}

if [ ${l_run_gotm} == "yes" ]; then
# set up namelists
cp ${nmldir}/*.nml ./

xmlfile=${title}.xml
cp ${xmldir}/${xmlfile} ./
sed -i.bk "s/_TAG_LAT/\"${lat}\"/g" ./${xmlfile}
sed -i.bk "s/_TAG_LON/\"${lon}\"/g" ./${xmlfile}
sed -i.bk "s/_TAG_MAXDEPTH/\"${maxdepth}\"/g" ./${xmlfile}

# set run parameters
${cmd_case_preproc} -xml ${xmlfile} -root ${GOTMWORK_ROOT} -data ${datadir} \
    -ds ${datestart} -de ${dateend} -method nc2dat_latlon
${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}

# use meteo data instead of fluxes
${cmd_nmlchange} -f airsea.nml -e calc_fluxes -v .true.
${cmd_nmlchange} -f airsea.nml -e fluxes_method -v 2
${cmd_nmlchange} -f airsea.nml -e back_radiation_method -v 1

# set turbulence model
${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99

# turn on CVMix
${cmd_nmlchange} -f kpp.nml -e lcvmix -v .true.

#######################################################################
#                              Run GOTM                               #
#######################################################################
${cmd_gotm} 2> log.${outname}

fi # l_run_gotm
#######################################################################
#                           Postprocessing                            #
#######################################################################

# plot surface forcing and profiles
source ${curdir}/case_postproc.sh
