#!/bin/bash

source "../../set_tools.sh"

cp ${nmldir}/*.nml ./

#--------------------------------
# MOMturb.nml
#--------------------------------
# airsea.nml
nml="airsea.nml"
${cmd_nmlchange} -f ${nml} -e calc_fluxes -v .false.
${cmd_nmlchange} -f ${nml} -e swr_method -v 0
${cmd_nmlchange} -f ${nml} -e albedo_method -v 0
${cmd_nmlchange} -f ${nml} -e heat_method -v 1
${cmd_nmlchange} -f ${nml} -e precip_method -v 1
${cmd_nmlchange} -f ${nml} -e momentum_method -v 1
${cmd_nmlchange} -f ${nml} -e u10_method -v 1
#--------------------------------
# epbl.nml
#--------------------------------
# gotmmean.nml
nml="gotmmean.nml"
${cmd_nmlchange} -f ${nml} -e rho_0 -v 1000.0
#--------------------------------
# gotmrun.nml
nml="gotmrun.nml"
${cmd_nmlchange} -f ${nml} -e title -v 'R19'
${cmd_nmlchange} -f ${nml} -e nlev -v 200
${cmd_nmlchange} -f ${nml} -e dt -v 60
${cmd_nmlchange} -f ${nml} -e name -v 'R19'
${cmd_nmlchange} -f ${nml} -e latitude -v 0.0
${cmd_nmlchange} -f ${nml} -e depth -v 200.0
${cmd_nmlchange} -f ${nml} -e start -v '2000-01-01 00:00:00'
${cmd_nmlchange} -f ${nml} -e stop -v '2000-01-05 00:00:00'
${cmd_nmlchange} -f ${nml} -e nsave -v 10
${cmd_nmlchange} -f ${nml} -e eq_state_method -v 4
${cmd_nmlchange} -f ${nml} -e T0 -v 20.0
${cmd_nmlchange} -f ${nml} -e dtr0 -v -0.20
${cmd_nmlchange} -f ${nml} -e dsr0 -v 0.80
#--------------------------------
# gotmturb.nml
#--------------------------------
# jhl.nml
#--------------------------------
# kpp.nml
#--------------------------------
# langmuir.nml
nml="langmuir.nml"
${cmd_nmlchange} -f ${nml} -e langmuir_number_method -v 0
#--------------------------------
# obs.nml
nml="obs.nml"
${cmd_nmlchange} -f ${nml} -e s_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e s_prof_file -v 'sprof_file.dat'
${cmd_nmlchange} -f ${nml} -e t_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e t_prof_file -v 'tprof_file.dat'
${cmd_nmlchange} -f ${nml} -e ustokes_method -v 0
#--------------------------------
# osm.nml
#--------------------------------
# seagrass.nml
#--------------------------------
