#!/bin/bash
# Setup and run GOTM for CORE-II
#
# Qing Li, 20180307

#######################################################################
#                              Set path                               #
#######################################################################

# root directory for gotmwork
workdir="${HOME}/models/gotm/gotmwork"

# scratch directory to run the case
scratchdir="${HOME}/work/gotmrun"

# setup paths and tools
source ${workdir}/set_tools.sh

# input data - surface fluxes
datadir="/Volumes/Qing_Work/data/COREII_IAF"

# input data - waves
uspdir="/Volumes/Qing_Work/data/WAVEWATCH_COREII"
uspdata="ww3.2008-2009_usp.nc"

# input data - Argo profiles for initialization
argodir="/Volumes/Qing_Work/data/obs/Argo"
argodata="WOD13_PFL_2000.nc"

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="COREII"

# set locations
lat=32
lon=145
maxdepth=525

# output file name
outname="gotm_out"

# starting and ending date - in the format of YYYYMMDD
datestart="20080701"
dateend="20081231"

# name of the turbulence model
turbmethod="KPP-CVMix"
# turbmethod="KPP-Original"

# case name
casename="${title}_LAT${lat}_LON${lon}_${turbmethod}_${datestart}-${dateend}"

#
l_run_gotm="yes"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${scratchdir}/${casename}"
mkdir -p ${rundir}
cd ${rundir}

if [ ${l_run_gotm} == "yes" ]; then
# set up namelists
cp ${nmldir}/*.nml ./

xmlfile=${title}.xml
cp ${xmldir}/${xmlfile} ./
sed -i.bk "s#_TAG_LAT#\"${lat}\"#g" ./${xmlfile}
sed -i.bk "s#_TAG_LON#\"${lon}\"#g" ./${xmlfile}
sed -i.bk "s#_TAG_MAXDEPTH#\"${maxdepth}\"#g" ./${xmlfile}

# general setup for the surface fluxes
${cmd_case_preproc} -xml ${xmlfile} -root ${workdir} -data ${datadir} \
    -ds ${datestart} -de ${dateend} -method nc2dat_latlon
${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}

# use meteo data instead of fluxes
${cmd_nmlchange} -f airsea.nml -e calc_fluxes -v .true.
${cmd_nmlchange} -f airsea.nml -e fluxes_method -v 2
${cmd_nmlchange} -f airsea.nml -e back_radiation_method -v 1

# processing Stokes drift data
${cmd_nc2dat_core2ww3_usp} -i ${uspdir}/${uspdata} -o "usp_file.dat" \
    -lat ${lat} -lon ${lon} -ds ${datestart} -de ${dateend}
${cmd_nmlchange} -f obs.nml -e ustokes_method -v 3
${cmd_nmlchange} -f obs.nml -e nfreq -v 3
${cmd_nmlchange} -f obs.nml -e ustokes_file -v "usp_file.dat"

# processing Argo data for initialization
tprof_name="tprof_file.dat"
sprof_name="sprof_file.dat"
${cmd_nc2dat_argo} -i ${argodir}/${argodata} -lat ${lat} -lon ${lon} \
    -r 3 -ot ${tprof_name} -os ${sprof_name} \
    -ds ${datestart} -de ${dateend}
${cmd_nmlchange} -f obs.nml -e t_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e t_prof_file -v ${tprof_name}
${cmd_nmlchange} -f obs.nml -e s_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e s_prof_file -v ${sprof_name}

# set turbulence model
${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99

# turn on CVMix
${cmd_nmlchange} -f kpp.nml -e lcvmix -v .true.

#######################################################################
#                              Run GOTM                               #
#######################################################################
gotm 2> log.${outname}

fi # l_run_gotm
#######################################################################
#                           Postprocessing                            #
#######################################################################

# plot surface forcing and profiles
source ${scpt_case_postproc}
