#!/bin/bash
# Setup and run GOTM for CORE-II
#
# Qing Li, 20180307

#######################################################################
#                              Set path                               #
#######################################################################

if [ -f './enviro_file' ]; then
source ./enviro_file
fi

if [ -z ${gotmexe} ]; then
gotmexe='gotm'
fi
echo "gotmexe is "${gotmexe}

if [ -z ${workdir} ]; then
# root directory for gotmwork
workdir="${HOME}/models/gotm/gotmwork"
fi
echo "workdir is "${workdir}

if [ -z ${scratchdir} ]; then
# scratch directory to run the case
scratchdir="${HOME}/work/gotmrun"
fi
echo "scratchdir is "${scratchdir}

# setup paths and tools
source ${workdir}/set_tools.sh

if [ -z ${dataroot} ]; then
# data directory
dataroot="${HOME}/work/gotmdata"
fi
echo "dataroot is "${dataroot}

# input data - surface fluxes
datadir="${dataroot}/COREII_IAF"

# input data - waves
uspdir="${dataroot}/WAVEWATCH_COREII"
uspdata="ww3.2008-2009_usp.nc"
wavdir="${dataroot}/WAVEWATCH_COREII"
wavdata="ww3.2008-2009.nc"

# input data - Argo profiles for initialization
argodir="${dataroot}/Argo"
argodata="WOD13_PFL_2000.nc"

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="COREII"

# set location, max depth and levels, grid zooming at surface
lat=50
lon=215
maxdepth=500
nlev=128
ddu=2
ddl=0

# run parameters
dt=1800
nsave=6

# output file name
outname="gotm_out"

# starting and ending date - in the format of YYYYMMDD
datestart="20090701"
dateend="20091231"

# name of the turbulence model
# turbmethod="KPPLT-ENTR"
# turbmethod="KPP-Original"
turbmethod="KPP-CVMix"

# case name
casename="${title}_LAT${lat}_LON${lon}_${turbmethod}_${datestart}-${dateend}"

#
l_run_gotm="yes"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${scratchdir}/${casename}"
mkdir -p ${rundir}
cd ${rundir}

if [ ${l_run_gotm} == "yes" ]; then
# set up namelists
cp ${nmldir}/*.nml ./

xmlfile=${title}.xml
cp ${xmldir}/${xmlfile} ./
sed -i.bk "s#_TAG_LAT#\"${lat}\"#g" ./${xmlfile}
sed -i.bk "s#_TAG_LON#\"${lon}\"#g" ./${xmlfile}
sed -i.bk "s#_TAG_MAXDEPTH#\"${maxdepth}\"#g" ./${xmlfile}

# set run parameters
${cmd_case_preproc} -xml ${xmlfile} -root ${workdir} -data ${datadir} \
    -ds ${datestart} -de ${dateend} -method nc2dat_latlon
${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
${cmd_nmlchange} -f gotmrun.nml -e dt -v ${dt}
${cmd_nmlchange} -f gotmrun.nml -e nsave -v ${nsave}
${cmd_nmlchange} -f gotmrun.nml -e nlev -v ${nlev}
${cmd_nmlchange} -f gotmmean.nml -e ddu -v ${ddu}
${cmd_nmlchange} -f gotmmean.nml -e ddl -v ${ddl}

# use meteo data instead of fluxes
${cmd_nmlchange} -f airsea.nml -e calc_fluxes -v .true.
${cmd_nmlchange} -f airsea.nml -e fluxes_method -v 2
${cmd_nmlchange} -f airsea.nml -e back_radiation_method -v 1

# processing Stokes drift data
${cmd_nc2dat_core2ww3} -i ${uspdir}/${uspdata} -o "usp_file.dat" \
    -lat ${lat} -lon ${lon} -ds ${datestart} -de ${dateend} -usp
${cmd_nmlchange} -f obs.nml -e ustokes_method -v 3
${cmd_nmlchange} -f obs.nml -e nfreq -v 3
${cmd_nmlchange} -f obs.nml -e usp_file -v "usp_file.dat"

# processing bulk wave parameter
${cmd_nc2dat_core2ww3} -i ${wavdir}/${wavdata} -o "wave_file.dat" \
    -lat ${lat} -lon ${lon} -ds ${datestart} -de ${dateend} \
    -v hs fp dir
${cmd_nmlchange} -f obs.nml -e wave_method -v 2
${cmd_nmlchange} -f obs.nml -e wave_file -v "wave_file.dat"

# processing Argo data for initialization
tprof_name="tprof_file.dat"
sprof_name="sprof_file.dat"
${cmd_nc2dat_argo} -i ${argodir}/${argodata} -lat ${lat} -lon ${lon} \
    -r 2 -ot ${tprof_name} -os ${sprof_name} \
    -ds ${datestart} -dr 10
${cmd_nmlchange} -f obs.nml -e t_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e t_prof_file -v ${tprof_name}
${cmd_nmlchange} -f obs.nml -e s_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e s_prof_file -v ${sprof_name}

# set turbulence method
source ${scpt_case_turbmethod}

#######################################################################
#                              Run GOTM                               #
#######################################################################
${gotmexe} 2> log.${outname}

fi # l_run_gotm
#######################################################################
#                           Postprocessing                            #
#######################################################################

# plot surface forcing and profiles
source ${scpt_case_postproc}
