#!/bin/bash

# root directory for gotmwork
workdir="${HOME}/models/gotm/gotmwork"

# setup paths and tools
source ${workdir}/set_tools.sh

# scratch directory
scratchdir="${HOME}/scratch"

# archive directory
archivedir="${HOME}/utleydata/qingli/gotmruns"

# directory for output
outputdatadir="${HOME}/work/gotmfigures"

# forcing scheme
forc_scheme="COREII"

# resolution
resolution="VR5m_DT60s"

# starting and ending date of simulation
datestart="20080615"
dateend="20091231"

# analysis
analysis="mldMean"

# analysis method
method="deltaR"

# loop over month
for month in Dec Feb Jun Aug DecY2; do
# for month in DecY2; do
# turbulent method
for turbmethod in KPP-CVMix KPPLT-ENTR EPBL OSMOSIS SMCLT SMC; do
# for turbmethod in SMC; do

    # starting and ending date of analysis
    case ${month} in
        "Dec")
            analystart="20081201"
            analyend="20081231"
            ;;
        "Feb")
            analystart="20090201"
            analyend="20090228"
            ;;
        "Jun")
            analystart="20090601"
            analyend="20090630"
            ;;
        "Aug")
            analystart="20090801"
            analyend="20090831"
            ;;
        "DecY2")
            analystart="20091201"
            analyend="20091231"
            ;;
        *)
            echo "Month ${month} not supported. Stop."
            exit 1
    esac

    # do analysis
    if [ -d ${scratchdir}/${resolution}/${turbmethod} ]; then
        inputdatadir=${scratchdir}/${resolution}/${turbmethod}
    elif [ -d ${archivedir}/${resolution}/${turbmethod} ]; then
        inputdatadir=${archivedir}/${resolution}/${turbmethod}
    else
        echo "GOTM data for case ${resolution}/${turbmethod} not found. Skip."
        continue
    fi
    ${cmd_gotm_analysis} -f ${forc_scheme} -t ${turbmethod} \
        -a ${analysis} -m ${method} \
        -ds ${datestart} -de ${dateend} -ds_a ${analystart} -de_a ${analyend} \
        -dir_in ${inputdatadir} \
        -dir_out ${outputdatadir}/${forc_scheme}
done
done
