#!/bin/bash

# setup paths and tools
source "../../set_tools.sh"

# archive directory
archivedir="${HOME}/utleydata/qingli/gotmruns"

# forcing scheme
forc_scheme="COREII"

# setup
setup="${forc_scheme}_VR1m_DT600s"

# starting and ending date of simulation
datestart="20080601"
dateend="20080630"

# analysis
analysis="mldMean"

# analysis method
method="deltaR"

# loop over month
# for month in Dec Feb Jun Aug DecY2; do
for month in Jun; do
# turbulent method
# for turbmethod in KPP-CVMix KPPLT-ENTR EPBL OSMOSIS SMCLT SMC; do
for turbmethod in KPPLT-ENTR; do

    # starting and ending date of analysis
    case ${month} in
        "Dec")
            analystart="20081201"
            analyend="20081231"
            ;;
        "Feb")
            analystart="20090201"
            analyend="20090228"
            ;;
        "Jun")
            analystart="20080601"
            analyend="20080630"
            ;;
        "Jul")
            analystart="20080701"
            analyend="20080731"
            ;;
        "Aug")
            analystart="20090801"
            analyend="20090831"
            ;;
        "DecY2")
            analystart="20091201"
            analyend="20091231"
            ;;
        *)
            echo "Month ${month} not supported. Stop."
            exit 1
    esac

    # do analysis
    if [ -d ${GOTMRUN_ROOT}/${setup}/${turbmethod} ]; then
        inputdatadir=${GOTMRUN_ROOT}/${setup}/${turbmethod}
    elif [ -d ${archivedir}/${setup}/${turbmethod} ]; then
        inputdatadir=${archivedir}/${setup}/${turbmethod}
    else
        echo "GOTM data for case ${setup}/${turbmethod} not found. Skip."
        continue
    fi
    ${cmd_gotm_analysis} -f ${forc_scheme} -t ${turbmethod} \
        -a ${analysis} -m ${method} \
        -ds ${datestart} -de ${dateend} -ds_a ${analystart} -de_a ${analyend} \
        -dir_in ${inputdatadir} \
        -dir_out ${GOTMFIG_ROOT}/${forc_scheme}
done
done
