#!/bin/bash
#
# This script finds all the processes named ${kproc} and kill them
#
# Qing Li, 20180410

kproc="case_run_multi"
klist=$(ps aux | grep ${kproc} | awk '{if($11!="grep") print $2}')

for i in ${klist}; do
    echo "Killing process ${i} ..."
    kill ${i}
done

