#!/bin/bash
# This script preprocess CORE-II data for GOTM input
#
# Qing Li, 20180503

#######################################################################
#                              Set path                               #
#######################################################################

# root directory for gotmwork
workdir="${HOME}/models/gotm/gotmwork"

# directory to save the data
scratchdir="${HOME}/scratch/gotmdata_core2"

# setup paths and tools
source ${workdir}/set_tools.sh

# data directory
dataroot="${HOME}/data_local"

# input data - surface fluxes
datadir="${dataroot}/COREII_IAF"

# input data - waves
uspdir="${dataroot}/WAVEWATCH_COREII"
uspdata="ww3.2008-2009_usp.nc"
wavdir="${dataroot}/WAVEWATCH_COREII"
wavdata="ww3.2008-2009.nc"

# input data - Argo profiles for initialization
argodir="${dataroot}/Argo"
argodata="WOD13_PFL_2000.nc"

# mask data
maskfile="${dataroot}/mask/ww3_mask_1dx1d.nc"

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="COREII"
maxdepth=2000

# starting and ending date - in the format of YYYYMMDD
datestart="20080115"
dateend="20091231"

# flag for dry run
l_dry_run="no"

#######################################################################
#                         Loop over locations                         #
#######################################################################
lon_start=$1
lon_end=$2
# lon_start=2
# lon_end=360
dlon=4
lat_start=-70
lat_end=70
dlat=4

# start outer loop over lon
lon=${lon_start}
while [ ${lon} -le ${lon_end} ]; do
# start inner loop over lat
lat=${lat_start}
while [ ${lat} -le ${lat_end} ]; do

    # check if it is a sea point
    l_sea=$(${cmd_is_sea} -fmask ${maskfile} -lat ${lat} -lon ${lon})

    # skip if not a sea point
    if [ ${l_sea} == "yes" ]; then

        # case name
        casename="${title}_LAT${lat}_LON${lon}_${datestart}-${dateend}"

        # dry run first and check the availability of argo profiles
        ${cmd_nc2dat_argo} -i ${argodir}/${argodata} -lat ${lat} -lon ${lon} \
            -r 2 -ds ${datestart} -dr 20 -dry
        nstate=$?

        if [ ${l_dry_run} == "no" ]; then
            # print case name
            echo ${casename}

            # skip if no argo profile is available
            if [ $nstate == 1 ]; then
                echo "[case_run_multi] No Argo profile available. Skip."
                lat=$((${lat}+${dlat}))
                continue
            fi

            # create run directory
            rundir="${scratchdir}/${casename}"
            mkdir -p ${rundir}
            cd ${rundir}

            # set up namelists
            cp ${nmldir}/*.nml ./

            xmlfile=${title}.xml
            cp ${xmldir}/${xmlfile} ./
            sed -i.bk "s#_TAG_LAT#\"${lat}\"#g" ./${xmlfile}
            sed -i.bk "s#_TAG_LON#\"${lon}\"#g" ./${xmlfile}
            sed -i.bk "s#_TAG_MAXDEPTH#\"${maxdepth}\"#g" ./${xmlfile}

            # set run parameters
            ${cmd_case_preproc} -xml ${xmlfile} -root ${workdir} -data ${datadir} \
                -ds ${datestart} -de ${dateend} -method nc2dat_latlon

            # processing Stokes drift data
            ${cmd_nc2dat_core2ww3} -i ${uspdir}/${uspdata} -o "usp_file.dat" \
                -lat ${lat} -lon ${lon} -ds ${datestart} -de ${dateend} -usp

            # processing bulk wave parameter
            ${cmd_nc2dat_core2ww3} -i ${wavdir}/${wavdata} -o "wave_file.dat" \
                -lat ${lat} -lon ${lon} -ds ${datestart} -de ${dateend} \
                -v hs fp dir

            # processing Argo data for initialization
            # save 12 initialization profiles
            for i in {1..12}; do
                mm=$(printf '%02d' ${i})
                argostart="${datestart:0:4}${mm}${datestart:6:2}"
                tprof_name="tprof_file_${argostart}.dat"
                sprof_name="sprof_file_${argostart}.dat"
                ${cmd_nc2dat_argo} -i ${argodir}/${argodata} -lat ${lat} -lon ${lon} \
                    -r 2 -ot ${tprof_name} -os ${sprof_name} \
                    -ds ${argostart} -dr 20 -maxd ${maxdepth}
            done
            rm ./*.nml
            rm ./*.xml
            rm ./*.bk

        fi # l_dry_run
    fi # l_sea

# end inner loop over lat
lat=$((${lat}+${dlat}))
done
# end outer loop over lon
lon=$((${lon}+${dlon}))
done

