#!/bin/bash
# This script checks the availability of the preprocessed COREII input data
# preproc_data and filter out those that are incomplete.
#
# Qing Li, 20180721


# setup paths and tools
source "../../set_tools.sh"

# data dir
datadir="${GOTMDATA_ROOT}/gotmdata_core2"

# name of the dataset
title="COREII"

# starting and ending date - in the format of YYYYMMDD
datestart="20080601"
dateend="20091231"

# loop over all cases
icounter=0
for icase in ${datadir}/*; do

    # check Argo data for initialization
    # check if 12 initialization profiles exist and are not empty
    l_bad="no"
    # for i in {1..12}; do
    for i in 2 8; do
        mm=$(printf '%02d' ${i})
        if [ ${i} -ge ${datestart:4:2} ]; then
            argostart="${datestart:0:4}${mm}${datestart:6:2}"
        else
            argostart="$((${datestart:0:4}+1))${mm}${datestart:6:2}"
        fi
        tprof_name="tprof_file_${argostart}.dat"
        sprof_name="sprof_file_${argostart}.dat"
        if [ ! -s ${icase}/${tprof_name} ]; then
            echo ${tprof_name}
            l_bad="yes"
            break
        fi
        if [ ! -s ${icase}/${sprof_name} ]; then
            echo ${sprof_name}
            l_bad="yes"
            break
        fi
    done
    if [ ${l_bad} == "yes" ]; then
        echo ${icase}
        icounter=$((icounter+1))
    fi
done
echo ${icounter}
