#!/bin/bash
# Setup and run GOTM for SOFSLES cases
#
# Qing Li, 20190820

#######################################################################
#                              Set paths                              #
#######################################################################

# setup paths and tools
source "../../set_tools.sh"

# input data directory
inputdir="${GOTMDATA_ROOT}/SOFS/LES"

# current path
curdir=$(pwd)

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
cname=$1
# cname="AprS"
title="SOFSLES_${cname}"
lat=-47.0
lon=141.9

if [[ ${cname} == "AprN" ]]; then
    start_time="2010-04-29 00:00:00"
    stop_time="2010-05-01 02:00:00"
    inputdata="${inputdir}/les-april_2010.no_stokes.nc"
    depth=350
elif [[ ${cname} == "AprS" ]]; then
    start_time="2010-04-29 00:00:00"
    stop_time="2010-05-01 04:30:00"
    inputdata="${inputdir}/les-april_2010.with_stokes.nc"
    depth=350
elif [[ ${cname} == "JunN" ]]; then
    start_time="2010-06-07 06:45:00"
    stop_time="2010-06-08 21:15:00"
    inputdata="${inputdir}/les-june_2010.no_stokes.nc"
    depth=500
elif [[ ${cname} == "JunS" ]]; then
    start_time="2010-06-07 06:45:00"
    stop_time="2010-06-08 23:45:00"
    inputdata="${inputdir}/les-june_2010.with_stokes.nc"
    depth=500
fi

# set levels, grid zooming at surface
nlev=${depth}
ddu=0
ddl=0

# run parameters
dt=600
nsave=3

# output file name
outname="gotm_out"

# name of the turbulence model
turbmethod=$2
# turbmethod="KPP-CVMix"

# case name
casename="${title}_${turbmethod}"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${GOTMRUN_ROOT}/${casename}"
mkdir -p ${rundir}
cd ${rundir}

# preprocess input data
${cmd_nc2dat_sofsles} -i ${inputdata} -c ${cname} -v TEMP -o tprof_file.dat -p
${cmd_nc2dat_sofsles} -i ${inputdata} -c ${cname} -v UVEL VVEL -o vel_prof_file.dat -p
${cmd_nc2dat_sofsles} -i ${inputdata} -c ${cname} -v USTKS VSTKS -o us_prof_file.dat -p
${cmd_nc2dat_sofsles} -i ${inputdata} -c ${cname} -v wbsfc -o heatflux_file.dat
${cmd_nc2dat_sofsles} -i ${inputdata} -c ${cname} -v tau_x tau_y -o tau_file.dat
${cmd_nc2dat_sofsles} -i ${inputdata} -c ${cname} -v u10 v10 -o u10_file.dat

# set salinity to be constant
cat > sprof_file.dat << SPROF
${start_time}  2  2
    0.0   35.0
 -500.0   35.0
SPROF

# set up namelists
cp ${nmldir}/*.nml ./

${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
${cmd_nmlchange} -f gotmrun.nml -e dt -v ${dt}
${cmd_nmlchange} -f gotmrun.nml -e nsave -v ${nsave}
${cmd_nmlchange} -f gotmrun.nml -e nlev -v ${nlev}
${cmd_nmlchange} -f gotmrun.nml -e depth -v ${depth}
${cmd_nmlchange} -f gotmrun.nml -e latitude -v ${lat}
${cmd_nmlchange} -f gotmrun.nml -e longitude -v ${lon}
${cmd_nmlchange} -f gotmrun.nml -e start -v "${start_time}"
${cmd_nmlchange} -f gotmrun.nml -e stop -v "${stop_time}"
${cmd_nmlchange} -f gotmrun.nml -e eq_state_method -v 4
${cmd_nmlchange} -f gotmrun.nml -e T0 -v 12.0
${cmd_nmlchange} -f gotmrun.nml -e S0 -v 35.0
${cmd_nmlchange} -f gotmrun.nml -e p0 -v 0.0
${cmd_nmlchange} -f gotmrun.nml -e dtr0 -v -0.195
${cmd_nmlchange} -f gotmrun.nml -e dsr0 -v 0.8
${cmd_nmlchange} -f gotmmean.nml -e rho_0 -v 1026.6
${cmd_nmlchange} -f gotmmean.nml -e ddu -v ${ddu}
${cmd_nmlchange} -f gotmmean.nml -e ddl -v ${ddl}

# calculate Langmuir number and enhancement factor from Stokes drift
${cmd_nmlchange} -f langmuir.nml -e langmuir_number_method -v 4

# set obs
${cmd_nmlchange} -f obs.nml -e t_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e t_prof_file -v "tprof_file.dat"
${cmd_nmlchange} -f obs.nml -e s_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e s_prof_file -v "sprof_file.dat"
${cmd_nmlchange} -f obs.nml -e vel_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e vel_prof_file -v "vel_prof_file.dat"
${cmd_nmlchange} -f obs.nml -e us_prof_method -v 2
${cmd_nmlchange} -f obs.nml -e us_prof_file -v "us_prof_file.dat"

# set airsea
${cmd_nmlchange} -f airsea.nml -e calc_fluxes -v .false.
${cmd_nmlchange} -f airsea.nml -e calc_evaporation -v .false.
${cmd_nmlchange} -f airsea.nml -e heat_method -v 2
${cmd_nmlchange} -f airsea.nml -e heatflux_file -v "heatflux_file.dat"
${cmd_nmlchange} -f airsea.nml -e momentum_method -v 2
${cmd_nmlchange} -f airsea.nml -e momentumflux_file -v "tau_file.dat"
${cmd_nmlchange} -f airsea.nml -e swr_method -v 0
${cmd_nmlchange} -f airsea.nml -e precip_method -v 0
${cmd_nmlchange} -f airsea.nml -e sst_method -v 0
${cmd_nmlchange} -f airsea.nml -e sss_method -v 0

# set turbulence method
source ${scpt_case_turbmethod}

#######################################################################
#                              Run GOTM                               #
#######################################################################
${cmd_gotm} 2> log.${outname}

