#!/bin/bash

source "../../../set_tools.sh"

cp ${nmldir}/*.nml ./

#--------------------------------
# MOMturb.nml
#--------------------------------
# airsea.nml
nml="airsea.nml"
${cmd_nmlchange} -f ${nml} -e heat_method -v 2
${cmd_nmlchange} -f ${nml} -e heatflux_file -v 'heat_flux.dat'
${cmd_nmlchange} -f ${nml} -e swr_method -v 2
${cmd_nmlchange} -f ${nml} -e albedo_method -v 0
${cmd_nmlchange} -f ${nml} -e swr_file -v 'swr_file.dat'
${cmd_nmlchange} -f ${nml} -e momentum_method -v 2
${cmd_nmlchange} -f ${nml} -e momentumflux_file -v 'tau_file.dat'
${cmd_nmlchange} -f ${nml} -e precip_method -v 2
${cmd_nmlchange} -f ${nml} -e precip_file -v 'pme_file.dat'
#--------------------------------
# epbl.nml
#--------------------------------
# gotmmean.nml
#--------------------------------
# gotmrun.nml
nml="gotmrun.nml"
${cmd_nmlchange} -f ${nml} -e title -v 'OSMOSIS_spring'
${cmd_nmlchange} -f ${nml} -e nlev -v 480
${cmd_nmlchange} -f ${nml} -e dt -v 1800
${cmd_nmlchange} -f ${nml} -e name -v 'OSMOSIS_spring'
${cmd_nmlchange} -f ${nml} -e latitude -v 49.0
${cmd_nmlchange} -f ${nml} -e longitude -v 0.0
${cmd_nmlchange} -f ${nml} -e depth -v 480.0
${cmd_nmlchange} -f ${nml} -e start -v '2012-12-25 00:00:00'
${cmd_nmlchange} -f ${nml} -e stop -v '2013-09-10 03:00:00'
${cmd_nmlchange} -f ${nml} -e nsave -v 6
${cmd_nmlchange} -f ${nml} -e eq_state_method -v 4
#--------------------------------
# gotmturb.nml
#--------------------------------
# jhl.nml
#--------------------------------
# kpp.nml
#--------------------------------
# langmuir.nml
nml="langmuir.nml"
${cmd_nmlchange} -f ${nml} -e langmuir_number_method -v 4
#--------------------------------
# obs.nml
nml="obs.nml"
${cmd_nmlchange} -f ${nml} -e s_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e s_prof_file -v 'sprof_file.dat'
${cmd_nmlchange} -f ${nml} -e t_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e t_prof_file -v 'tprof_file.dat'
${cmd_nmlchange} -f ${nml} -e extinct_method -v 7
${cmd_nmlchange} -f ${nml} -e A -v 0.57
${cmd_nmlchange} -f ${nml} -e g1 -v 0.55
${cmd_nmlchange} -f ${nml} -e g2 -v 17.0
${cmd_nmlchange} -f ${nml} -e ustokes_method -v 4
${cmd_nmlchange} -f ${nml} -e usdelta_file -v 'ustokes_file.dat'
#--------------------------------
# osm.nml
nml="osm.nml"
${cmd_nmlchange} -f ${nml} -e h_i -v 100.0
#--------------------------------
# seagrass.nml
#--------------------------------
