#!/bin/bash
# Setup and run GOTM for OCS Papa
#
# Qing Li, 20171105

#######################################################################
#                              Set path                               #
#######################################################################

workdir="${HOME}/models/gotm/gotmwork"
scratchdir="${HOME}/work/gotmrun"
tooldir="${workdir}/tools"
nmldir="${workdir}/namelist"
xmldir="${workdir}/data"
cmd_nc2dat_cdip="${tooldir}/nc2dat_cdip_spec"
cmd_nmlchange="${tooldir}/nmlchange"
cmd_case_preproc="${tooldir}/case_preproc"
cmd_plotpfl="${tooldir}/plotpfl"
cmd_plotts="${tooldir}/plotts"

#######################################################################
#                           Set parameters                            #
#######################################################################

datadir="${HOME}/data/OCS/Papa/2016"
specdata="${HOME}/data/CDIP/Papa/166p1_rt.nc"
title="OCSPapa"
outname="ocspapa"
# start and end date
datestart="20160101"
dateend="20161231"
turbmethod="KPP-Original"
casename="${title}_${turbmethod}_${datestart}-${dateend}"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run dir
rundir="${scratchdir}/${casename}"
mkdir -p ${rundir}

cd ${rundir}
# cp ${nmldir}/*.nml ./
# # read data.xml
# xmlfile=${title}.xml
# cp ${xmldir}/${xmlfile} ./
# ${cmd_case_preproc} -xml ${xmlfile} -root ${workdir} -data ${datadir} \
#     -ds ${datestart} -de ${dateend}

# # processing wave spectrum data
# ${cmd_nc2dat_cdip} -i ${specdata} -o "spec_file.dat" -ds ${datestart} \
#     -de ${dateend}

# ${cmd_nmlchange} -f obs.nml -e spec_method -v 2
# ${cmd_nmlchange} -f obs.nml -e spec_file -v 'spec_file.dat'
# ${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
# ${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
# ${cmd_nmlchange} -f gotmturb.nml -e turb_method -v 99

#######################################################################
#                              Run GOTM                               #
#######################################################################
# gotm 2> log.${outname}

#######################################################################
#                           Postprocessing                            #
#######################################################################

pp_mmdd_start=("0101" "0201" "0301" "0401" "0501" "0601" "0701" "0801" "0901" "1001" "1101" "1201")
pp_mmdd_end=("0131" "0228" "0331" "0430" "0531" "0630" "0731" "0831" "0930" "1031" "1130" "1231")
pp_year="2016"
pp_vars="temp temp_obs salt salt_obs"
# for i in {0..11}; do
#     pp_date_start="${pp_year}${pp_mmdd_start[i]}"
#     pp_date_end="${pp_year}${pp_mmdd_end[i]}"
#     for pp_var in ${pp_vars}; do
#         ${cmd_plotpfl} -f ${outname}.nc -v ${pp_var} -o "${pp_var}_${pp_date_start}-${pp_date_end}.pdf" -ds ${pp_date_start} -de ${pp_date_end}
#     done
# done

pp_date_start=${datestart}
pp_date_end=${dateend}
for pp_var in ${pp_vars}; do
    # ${cmd_plotpfl} -f ${outname}.nc -v ${pp_var} -o "${pp_var}_${pp_date_start}-${pp_date_end}.pdf" -ds ${pp_date_start} -de ${pp_date_end} -ptype contourf
    ${cmd_plotts} -f ${outname}.nc -v tx ty heat I_0 -o "gotm_ts_surface_${pp_date_start}-${pp_date_end}.pdf" -ds ${pp_date_start} -de ${pp_date_end}
done
