#!/bin/bash
# Setup and run GOTM for OCS Papa
#
# Qing Li, 20171105

workdir="${HOME}/models/gotm/gotmwork"
tooldir="${workdir}/tools"
nmldir="${workdir}/namelist"

#######################################################################
#                         Prepare input data                          #
#######################################################################
datadir="${HOME}/data/OCSPapa/2016"

# momentum flux (N/m2)
fname_tau="tau50n145w_hr.cdf"
vname_taux="TX_442"
vname_tauy="TY_443"
oname_tau="tau.dat"

# shortwave radiation (W/m2)
fname_swr="swnet50n145w_hr.cdf"
vname_swr="SWN_1495"
oname_swr="swr.dat"

# heat flux except shortwave (W/m2)
fname_hf=""
vname_hf=""
oname_hf="heatflux.dat"

# sst (degC)
fname_sst="sst50n145w_hr.cdf"
vname_sst="T_25"
oname_sst="sst.dat"

# sss (psu)
fname_sss="sss50n145w_hr.cdf"
vname_sss="S_41"
oname_sss="sss.dat"

# temperature profile (degC)
fname_tprof="t50n145w_hr.cdf"
vname_tprof="T_20"
oname_tprof="tprof.dat"

# salinity profile (psu)
fname_sprof="s50n145w_hr.cdf"
vname_sprof="S_41"
oname_sprof="sprof.dat"

# start and end date
datestart="20160325"
dateend="20160411"

# nc2dat
${tooldir}/nc2dat -i ${datadir}/${fname_tau} -v ${vname_taux} ${vname_tauy} \
    -o ${oname_tau} -ds ${datestart} -de ${dateend}
${tooldir}/nc2dat -i ${datadir}/${fname_swr} -v ${vname_swr} \
    -o ${oname_swr} -ds ${datestart} -de ${dateend}
${tooldir}/nc2dat -i ${datadir}/${fname_sst} -v ${vname_sst} \
    -o ${oname_sst} -ds ${datestart} -de ${dateend}
${tooldir}/nc2dat -i ${datadir}/${fname_tprof} -v ${vname_tprof} \
    -o ${oname_tprof} -ds ${datestart} -de ${dateend}
${tooldir}/nc2dat -i ${datadir}/${fname_sprof} -v ${vname_sprof} \
    -o ${oname_sprof} -ds ${datestart} -de ${dateend}

#######################################################################
#                          Prepare namelist                           #
#######################################################################
cp ${nmldir}/*.nml ./
${tooldir}/nmlchange -f airsea.nml -e momentumflux_file -v ${oname_tau}
${tooldir}/nmlchange -f airsea.nml -e heatflux_file -v ${oname_hf}
${tooldir}/nmlchange -f airsea.nml -e swr_file -v ${oname_swr}
${tooldir}/nmlchange -f airsea.nml -e sst_file -v ${oname_sst}
${tooldir}/nmlchange -f airsea.nml -e sss_file -v ${oname_sss}
${tooldir}/nmlchange -f obs.nml -e t_prof_file -v ${oname_tprof}
${tooldir}/nmlchange -f obs.nml -e s_prof_file -v ${oname_sprof}

#######################################################################
#                              Run GOTM                               #
#######################################################################

