#!/bin/bash
#
# Manually parallel run by submitting multiple jobs

# lon_slist=(  2  70 126 166 194 226 266 322)
# lon_elist=( 66 122 162 190 222 262 318 360)
# lon_slist=(  2  78 138 178 210 234 266 322)
# lon_elist=( 74 134 174 206 230 262 318 360)
# lon_slist=(  2  70 126 170 202 238 282 330)
# lon_elist=( 66 122 166 198 234 278 326 360)
lon_slist=(  2  126 202 278 )
lon_elist=( 122 198 274 360 )

tmethod_list=( "KPP-CVMix" "KPP-ROMS" "KPPLT-EFACTOR" "KPPLT-ENTR" "KPPLT-RWHGK" "SMC" "SMCLT" "EPBL" "EPBL-LT" "OSMOSIS" "K-EPSILON-SG" )

# tmethod=${tmethod_list[0]}
# echo ${tmethod}
# for i in {0..3}; do
#     lon_start=${lon_slist[i]}
#     lon_end=${lon_elist[i]}

#     # Preprocess input data
#     # ./preproc_data ${lon_start} ${lon_end} > log.${i} &

#     # Run GOTM
#     ./case_run_multi ${lon_start} ${lon_end} ${tmethod} > log.${i} &
# done

for j in {1..4}; do
    tmethod=${tmethod_list[j]}
    echo ${tmethod}
    # Run GOTM
    ./case_run_multi 2 360 ${tmethod} > log.${j} &
done
