#!/bin/bash
#
# Extract data from archive
#
# Qing Li, 20181113

# usage
function print_usage(){
    echo "usage: gotm_extract_data [-h] [-c CASENAME] [-s SETUPNAME] [-m TURBMETHOD]"
    echo ""
    echo "Extract data from archive."
    echo ""
    echo "arguments:"
    echo "  -h            show this help message and exit"
    echo "  -c CASENAME   case name"
    echo "  -s SETUPNAME  setup name"
    echo "  -m TURBMETHOD turbulence method"
    exit 1
}

# parse input arguments
casename="none"
casesetup="none"
turbmethod="none"
while getopts hc:s:m: options
do
    case ${options} in
        # help
        h) print_usage ;;
        # case name
        c) casename=${OPTARG} ;;
        # case setup
        s) casesetup=${OPTARG} ;;
        # turbulence method
        m) turbmethod=${OPTARG} ;;
        \?) echo "Unknown option -${OPTARG}"
            exit 1 ;;
    esac
done

# check input arguments
if [[ ${casename} == "none" ]]; then
    echo "Missing option -c [case name]"
    exit 1
fi

if [[ ${casesetup} == "none" ]]; then
    echo "Missing option -s [case setup]"
    exit 1
fi

# check environment variables
if [[ -z ${GOTMRUN_ROOT} ]]; then
    echo "Environment variable GOTMRUN_ROOT not set. Run 'source set_tools.sh' first."
    exit 1
fi

if [[ -z ${GOTMARCHIVE_ROOT} ]]; then
    echo "Environment variable GOTMARCHIVE_ROOT not set. Run 'source set_tools.sh' first."
    exit 1
fi

# run directory
run_dir=${GOTMRUN_ROOT}/${casename}/${casesetup}

# archive directory
arc_dir=${GOTMARCHIVE_ROOT}/${casename}/${casesetup}

# current directory
cur_dir=$(pwd)

# extract data
echo "Extracting data to ..."
echo "  ${run_dir}"
mkdir -p ${run_dir}
cd ${run_dir}
if [[ ${turbmethod} == "none" ]]; then
    for f in ${arc_dir}/*.tar.gz; do
        echo "    ${f} ..."
        tar -zxf ${f}
    done
else
    f=${arc_dir}/${turbmethod}.tar.gz
    echo "    ${f} ..."
    tar -zxf ${f}
fi
cd ${cur_dir}

