#!/usr/bin/env python3
"""
Qing Li, 20171213
"""

import matplotlib.pyplot as plt
import numpy as np
import argparse
import sys
import datetime
from netCDF4 import Dataset, num2date
from gotmtool import *

def main():

    # process input arguments
    parser = argparse.ArgumentParser(description="""
        Plot time series from GOTM output. Accept multiple variables.""")
    parser.add_argument('-f', '--file', action='store', dest='fname',
            metavar='FILENAME', help='Input GOTM data')
    parser.add_argument('-v', '--variable', action='store', dest='vname',
            metavar='VARNAME', nargs='+', help='Variable name')
    parser.add_argument('-o', '--output', action='store', dest='fname_out',
            metavar='FIGNAME', help='Output figure name')
    parser.add_argument('-ds', '--date_start', action='store', dest='date_start',
            metavar='STARTDATE',
            help='Starting date of input data, in the format of YYYYMMDD')
    parser.add_argument('-de', '--date_end', action='store', dest='date_end',
            metavar='ENDDATE',
            help='Ending date of input data, in the format of YYYYMMDD')
    parser.add_argument('--version', action='version', version='%(prog)s: 1.0')
    # parsing arguments and save to args
    args = parser.parse_args()

    # check input
    if not args.fname or not args.vname or not args.fname_out:
        print('GOTM netCDF data, variable name, and output figure name are required. Stop.\n')
        parser.print_help()
        sys.exit(1)

    # read data
    fin = Dataset(args.fname, 'r')
    varlist = fin.variables.keys()

    # read time
    if 'time' in varlist:
        nctime = fin.variables['time']
    elif 'TIME' in varlist:
        nctime = fin.variables['TIME']
    else:
        print('Time dimension is required and should have the name \"time\" or \"TIME\"')

    # get starting and ending indices
    tidx_start, tidx_end = nctime_indices(nctime, args.date_start,
            args.date_end)

    # nctime -> datetime
    dttime = nctime_to_datetime(nctime, tidx_start, tidx_end)

    # print some message
    print_dttime_range(dttime)

    # number of subfigure
    nv = len(args.vname)
    # set figure size
    fig_width = 6
    fig_height = 4+0.8*(nv-1)
    if nv == 1:
        # single figure
        # read data
        varname = args.vname[0]
        ncvar = fin.variables[varname]
        dat = ncread_ts(ncvar, tidx_start, tidx_end)
        # skip the first data point
        plt.plot(dttime[1:], dat[1:], '-k', linewidth=1.5)
        f = plt.gcf()
        f.set_size_inches(fig_width, fig_height)
        plt.ylabel(varname)
        # use scientific notation in y-axis label
        ax = plt.gca()
        ax.ticklabel_format(axis='y', style='sci', scilimits=(-2,2))
        # make the exponent labels cleaner
        ax.yaxis.offsetText.set_fontsize(8)
        ax.yaxis.offsetText.set_x(-0.02)
    else:
        # subplot, share x axis
        f, axarr = plt.subplots(nv, sharex=True)
        f.set_size_inches(fig_width, fig_height)
        for i in range(nv):
            # read data
            varname = args.vname[i]
            ncvar = fin.variables[varname]
            dat = ncread_ts(ncvar, tidx_start, tidx_end)
            # skip the first data point
            ax = axarr[i]
            ax.plot(dttime[1:], dat[1:], '-k', linewidth=1.5)
            ax.set_ylabel(varname)
            # use scientific notation in y-axis label
            ax.ticklabel_format(axis='y', style='sci', scilimits=(-2,2))
            # make the exponent labels cleaner
            ax.yaxis.offsetText.set_fontsize(8)
            ax.yaxis.offsetText.set_x(-0.02)
    # x label date
    plt.gcf().autofmt_xdate()

    # save figure
    figname = args.fname_out
    plt.savefig(figname)

if __name__ == "__main__":
    main()
